language: python
sudo: false
# command to install dependencies
install:
  - pip install virtualenv python-coveralls
# # command to run tests
script: python setup.py test
after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=balrog --cov-report=term-missing tests
  - coveralls
notifications:
    email:
        - opensource-tests@paylogic.com
